## Numpy Basics

In [3]:
import numpy as np

In [5]:
#Convert python list into an array
mylist = [1,2,3,4]
arr = np.array(mylist)
print(arr)

[1 2 3 4]


In [6]:
#arange function - creates array of number from 0 up until that number 
a = np.arange(0,10) #just like range fn
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros((5,5)) #create two dimensional array - create 5x5 tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.zeros((1,10)) #1 row, 10 cols

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,4)) #2x4 matrix of 1s
#return type is float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.random.randint(0,100) #returns a random number between 0 and 100

84

In [16]:
np.random.randint(0,100,(5,5)) 
'''array of random
integers. 5x5 matrix of random nos. from 0 to 100'''
 #uniform distribution: every number from 0-100 has same likelihood

'array of random\nintegers. 5x5 matrix of random nos. from 0 to 100'

In [17]:
np.linspace(0,10, 6) #6 numbers from 0-10 and space between them is the same

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
np.linspace(0,10,101) #101 nums between 0 and 10 all evenly spaced

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [19]:
np.random.seed(101) #set seed in R
np.random.randint(0,100,10) #have to call it just before running a rng

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [20]:
arr = np.random.randint(0,100,10)

In [23]:
arr.max() #max value of the array

93

In [24]:
arr.min()#min value of the array

4

In [25]:
arr.argmax() #index location of the max value

8

In [26]:
arr.reshape(2,5) #max 1x10 into 2x5 array

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

In [7]:
#range of numbers then reshape
mat = np.arange(0,100).reshape(10,10) 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
mat[5,2] #indexing

52

In [32]:
mat[:,2] #to get an entire column in form of an array

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [34]:
mat[2,:].reshape(5,2) #select row of a matrix

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [35]:
mat>50 #returns matrix of boolean value, indicating where matrix is not greater than and is greater than 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [36]:
mat[mat>50] #only vlues greater than 50. Like R

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Pandas
- Built on top of Numpy

In [37]:
import pandas as pd

In [40]:
df = pd.read_csv("salaries.csv")
print(df) #similar to numpy array or matrix

     Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27


In [41]:
print(df["Salary"]) #you can select the column with column name in a dataframe

0     50000
1    120000
2     80000
Name: Salary, dtype: int64


In [42]:
#Reading Multiple columns of data
print(df[["Name","Salary"]]) #its like R c()

     Name  Salary
0    John   50000
1   Sally  120000
2  Alyssa   80000


In [44]:
print(df["Salary"].min()) #minimum salary value, min of a column

50000


In [46]:
ser_of_bool = df['Age']>30 #returns series of bool values

In [48]:
ser_of_bool
#where is the df age column greater than 30?

0     True
1     True
2    False
Name: Age, dtype: bool

In [50]:
df[ser_of_bool] #get all the rows where this condition is true

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [52]:
df["Age"].unique()  #the unique values of Age

array([34, 45, 27], dtype=int64)

In [53]:
df["Age"].nunique() #number of uniqe values

3

In [56]:
df.columns #gives back list of column names

Index(['Name', 'Salary', 'Age'], dtype='object')

In [58]:
df.info()  #similar to str in R

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
Name      3 non-null object
Salary    3 non-null int64
Age       3 non-null int64
dtypes: int64(2), object(1)
memory usage: 152.0+ bytes


In [60]:
df.describe() #returns summary statistics of df for numerical columns

Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000

In [63]:
df.index #no. of columns i assume, not entirely clear

RangeIndex(start=0, stop=3, step=1)

In [64]:
mat = np.arange(0,50).reshape(5,10)

In [65]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [8]:
df = pd.DataFrame(data = mat)
df #show pandas data frame
#we can also pass index and columns

NameError: name 'pd' is not defined

In [70]:
mat = np.arange(0,10).reshape(5,2)
mat

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [72]:
df = pd.DataFrame(data = mat, columns = ["A","B"])
df

A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

## Exercises in pandas and numpy

In [85]:
#1 import pands and numpy
#2 Set numpy's rng seed to 101
np.random.seed(101)
#3 create 100x5 matrix with random ints from 1-100
mat = np.random.randint(1,101,(100,5)) #upper limit is exclusive

In [87]:
#4 Use dataframe to read array as a df
df = pd.DataFrame(data =mat)

In [90]:
#5 Rename pandas columns to ['f1','f2','f3','f4','label']
df.columns = ["f1","f2","f3","f4","label"]
df.columns

Index(['f1', 'f2', 'f3', 'f4', 'label'], dtype='object')

In [97]:
#6. Create df with cols from A-D and 50 rows of data. Data is random nos. from 0-100
mat = np.random.randint(0,101,(50,4))
col_names = ["A","B","C","D"]
col_names = "A B C D".split()
df = pd.DataFrame(data = mat, columns = col_names)

#